server:
  port: 8888
spring:
  application:
    name: cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/love219841207/spring-cloud.git
          searchPaths: cloud-config-server
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:7761/eureka/,http://peer2:8761/eureka/,http://peer3:9761/eureka/
