endpoints:
  shutdown:
    enabled: true
    sensitive: false
spring:
  application:
    name: biz
server:
  port: 8081
eureka:
  instance: 
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30 
  client:
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://peer1:7761/eureka/,http://peer2:8761/eureka/,http://peer3:9761/eureka/

management.security.enabled: false 
