endpoints:
  shutdown:
    enabled: true
    sensitive: false
server:
  port: 8081
eureka:
  instance: 
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 30 
  client:
    registry-fetch-interval-seconds: 5
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://peer1:7761/eureka/,http://peer2:8761/eureka/,http://peer3:9761/eureka/

management.security.enabled: false 

spring:
  application:
    name: biz
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://mysql:3306/food?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&rewriteBatchedStatements=TRUE&useSSL=false
    username: root
    password: Mysql123!
    initialSize: 5
    minIdle: 5
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database: mysql
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
    
mybatis:
    type-aliases-package: com.think.cloud.service.user.model
    mapper-locations: classpath:mapper/*.xml

mapper:
    mappers:
        - com.think.cloud.service.user.util.MyMapper
    not-empty: false
    identity: MYSQL

pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
